import 'dart:math';

const Map<String, String> KATAKANA_MAP = {
  'ア': 'a',
  'イ': 'i',
  'ウ': 'u',
  'エ': 'e',
  'オ': 'o',
  'カ': 'ka',
  'キ': 'ki',
  'ク': 'ku',
  'ケ': 'ke',
  'コ': 'ko',
  'サ': 'sa',
  'シ': 'shi',
  'ス': 'su',
  'セ': 'se',
  'ソ': 'so',
  'タ': 'ta',
  'チ': 'chi',
  'ツ': 'tsu',
  'テ': 'te',
  'ト': 'to',
  'ナ': 'na',
  'ニ': 'ni',
  'ヌ': 'nu',
  'ネ': 'ne',
  'ノ': 'no',
  'ハ': 'ha',
  'ヒ': 'hi',
  'フ': 'fu',
  'ヘ': 'he',
  'ホ': 'ho',
  'マ': 'ma',
  'ミ': 'mi',
  'ム': 'mu',
  'メ': 'me',
  'モ': 'mo',
  'ヤ': 'ya',
  'ユ': 'yu',
  'ヨ': 'yo',
  'ラ': 'ra',
  'リ': 'ri',
  'ル': 'ru',
  'レ': 're',
  'ロ': 'ro',
  'ワ': 'wa',
  'ヲ': 'wo',
  'ン': 'n',
  'ガ': 'ga',
  'ギ': 'gi',
  'グ': 'gu',
  'ゲ': 'ge',
  'ゴ': 'go',
  'ザ': 'za',
  'ジ': 'ji',
  'ズ': 'zu',
  'ゼ': 'ze',
  'ゾ': 'zo',
  'ダ': 'da',
  'ヂ': 'ji',
  'ヅ': 'zu',
  'デ': 'de',
  'ド': 'do',
  'バ': 'ba',
  'ビ': 'bi',
  'ブ': 'bu',
  'ベ': 'be',
  'ボ': 'bo',
  'パ': 'pa',
  'ピ': 'pi',
  'プ': 'pu',
  'ペ': 'pe',
  'ポ': 'po',
  'キャ': 'kya',
  'キュ': 'kyu',
  'キョ': 'kyo',
  'シャ': 'sha',
  'シュ': 'shu',
  'ショ': 'sho',
  'チャ': 'cha',
  'チュ': 'chu',
  'チョ': 'cho',
  'ニャ': 'nya',
  'ニュ': 'nyu',
  'ニョ': 'nyo',
  'ヒャ': 'hya',
  'ヒュ': 'hyu',
  'ヒョ': 'hyo',
  'ミャ': 'mya',
  'ミュ': 'myu',
  'ミョ': 'myo',
  'リャ': 'rya',
  'リュ': 'ryu',
  'リョ': 'ryo',
  'ギャ': 'gya',
  'ギュ': 'gyu',
  'ギョ': 'gyo',
  'ジャ': 'ja',
  'ジュ': 'ju',
  'ジョ': 'jo',
  'ビャ': 'bya',
  'ビュ': 'byu',
  'ビョ': 'byo',
  'ピャ': 'pya',
  'ピュ': 'pyu',
  'ピョ': 'pyo'
};

const Map<String, String> HIRAGANA_MAP = {
  'あ': 'a',
  'い': 'i',
  'う': 'u',
  'え': 'e',
  'お': 'o',
  'か': 'ka',
  'き': 'ki',
  'く': 'ku',
  'け': 'ke',
  'こ': 'ko',
  'さ': 'sa',
  'し': 'shi',
  'す': 'su',
  'せ': 'se',
  'そ': 'so',
  'た': 'ta',
  'ち': 'chi',
  'つ': 'tsu',
  'て': 'te',
  'と': 'to',
  'な': 'na',
  'に': 'ni',
  'ぬ': 'nu',
  'ね': 'ne',
  'の': 'no',
  'は': 'ha',
  'ひ': 'hi',
  'ふ': 'fu',
  'へ': 'he',
  'ほ': 'ho',
  'ま': 'ma',
  'み': 'mi',
  'む': 'mu',
  'め': 'me',
  'も': 'mo',
  'や': 'ya',
  'ゆ': 'yu',
  'よ': 'yo',
  'ら': 'ra',
  'り': 'ri',
  'る': 'ru',
  'れ': 're',
  'ろ': 'ro',
  'わ': 'wa',
  'を': 'wo',
  'ん': 'n'
};

// todo: should keep a frequency map and give higher probability of next draw to lower frequencies
class RandDataProvider<K, V> {
  final Map<K, V> _data;

  const RandDataProvider({required Map<K, V> data}) : _data = data;

  static const RandDataProvider<String, String> HIRAGANA =
      RandDataProvider(data: HIRAGANA_MAP);
  static const RandDataProvider<String, String> KATAKANA =
      RandDataProvider(data: KATAKANA_MAP);

  (K, V) get() {
    final random = Random();
    final entry = _data.entries.elementAt(random.nextInt(HIRAGANA_MAP.length));
    return (entry.key, entry.value);
  }
}
