[tool.poetry]
name = "tts"
version = "0.1.0"
description = ""
authors = ["Pasqg <pasquale.giovenale@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.40.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
